### ISSUE TITLE
Lanyard API not working

### ISSUE THREAD

**Issue by Avyansh0001** [Phineas/lanyard#64] opened 2021-08-10 11:11 UTC
On my Website [avyanshralph.vercel.app](https://avyanshralph.vercel.app) The Discord Activity status is not showing when hosted on vercel but it shows when I host it locally... Pls tell the reason behind this issue

Regards,
Avyansh Ralph 
Owner of Airdown

**Comment by Phineas** [comment] 2021-08-10 11:13
I don't think your deployment is working. I can't see any requests to Lanyard from your site or any references to Lanyard in your site's bundle.

**Comment by Avyansh0001** [comment] 2021-08-10 11:23
Oh so can you pls help me cause it is the first time I am using Lanyard API

**Comment by Phineas** [comment] 2021-08-10 16:50
The issue is with your Vercel deployment, not your Lanyard implementation. It seems to work fine on your Netlify deployment. I'll close this for now - please ask in the #support channel in the Lanyard Discord if you need help with your implementation.

**Closed by Phineas** 2021-08-10 16:50 UTC
